// generated by stringer -type=typ /home/daniel/src/goprj/src/github.com/DanielMorsing/gonzbee/par2/blocktype.go; DO NOT EDIT

package par2

import "fmt"

const _typ_name = "typeUnknowntypeMaintypeFileDesctypeIFSCtypeRecvSlictypeCreator"

var _typ_index = [...]uint8{11, 19, 31, 39, 51, 62}

func (i typ) String() string {
	if i < 0 || i >= typ(len(_typ_index)) {
		return fmt.Sprintf("typ(%d)", i)
	}
	hi := _typ_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _typ_index[i-1]
	}
	return _typ_name[lo:hi]
}
